version: "3.8"

services:
  bot:
    image: dsi-join-list:latest
    build:
      .
    volumes:
      - ./config.json:/srv/DSI-Join-List/config.json
    networks:
      - dsinet
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    networks:
      - dsinet
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dsijoin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dsidata:/var/lib/postgresql/data

networks:
  dsinet:
volumes:
  dsidata:
